SYRINGE_WIDTH = 15
SYRINGE_HEIGHT = 34
SYRINGE_IDX = 0
SYRINGE_START_X = 25
SYRINGE_START_Y = 58

SYRINGE_SPEED = 3

VIRUS_WIDTH = 8
VIRUS_HEIGHT = 8
VIRUS_IDX = 0
VIRUS_START_X = 4
VIRUS_START_Y = 44

VIRUS_SPEED_X = 1.5
VIRUS_SPEED_Y = 0.5
